//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.5.15
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: nand_gate ()
//
module tt_um_nand // "tb.dut_inst"
(
    input logic A,
    input logic B,
    output logic Z
);

//------------------------------------------------------------------------------
// Method process: do_nand (nand_gate.h:11:5) 

always_comb 
begin : do_nand     // nand_gate.h:11:5
    Z = !(A && B);
end

endmodule


