//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.5.15
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: nand_gate ()
//
module tt_um_nand // "tb.dut_inst"
(
input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

wire A = ui_in[0];
wire B = ui_in[1];
reg Z;
assign uo_out[0] = Z;
assign uo_out[7:1] = 7'b0000000;
assign uio_oe[7:0] = 8'b00000000;
assign uio_out[7:0] = 8'b00000000;
//
//------------------------------------------------------------------------------
// Method process: do_nand (nand_gate.h:11:5) 

always_comb 
begin : do_nand     // nand_gate.h:11:5
    Z = !(A && B);
end

endmodule


